# Site settings
title: "Monaj's Resume"
description: "Resume using Github Pages."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar: "true"
resume_name: "Monaj Bid"
resume_title: "Contact Me"

# used for the contact button in _layouts/resume.html
resume_contact_email: "manojbid2003@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone: "+918918991088"
resume_contact_address: "Durgapur"

resume_header_contact_info: "Durgapur • +918918991088 • souvikpramanik585@gmail.com"
display_header_contact_info: "false"

resume_header_intro: "<p>Final year in Computer Science graduate with a passion for learning and innovation. Seeking an entry-level position in the tech industry where I can use my skills and knowledge to make a positive impact</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work: "yes"

# Decide which sections to use
# comment out to hide
# resume_section_experience: true
resume_section_education: true
resume_section_projects: true
resume_section_skills: true
resume_section_recognition: true
# resume_section_links: true
resume_section_associations: true
resume_section_interests: true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url: "https://github.com/souvik-pramanik"
  resume_twitter_url: "http://twitter.com/snaptokon"
  # resume_dribbble_url: "https://dribbble.com/jag"
  resume_facebook_url: "http://m.facebook.com/snaptokon"
  resume_linkedin_url: "https://www.linkedin.com/in/snaptokon"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url: "http://joelglovier.com"
  resume_medium_url: "https://medium.com/@snaptokon"
resume_print_social_links: true

# Design settings
resume_theme: default
# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
